version: '3.9'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: nab
      DB_USERNAME: root
      DB_PASSWORD: root
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: nab
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: {}

